server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      client.dns.lookup: use_all_dns_ips
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
    consumer:
      group-id: orders-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
      enable-auto-commit: false   # usa commits gestionados por el contenedor
    listener:
      ack-mode: RECORD
#    properties:
#      client:
#        dns:
#          lookup: use_all_dns_ips

app:
  topics:
    orders: orders.created.v1

